/** Generated by AI Growth OS — merge into app/layout.tsx metadata */
export const aigosMetadata: Record<string, unknown> = {
  alternates: { canonical: "github://akibraza3723/Vantish/client/design.md" },
  // Open Graph tags also in head-snippet.html
  openGraph: { url: "https://akibraza3723/vantish" },
  // FAQ JSON-LD is in head-snippet.html (not Metadata API)
  other: { "aigos-faq": "see head-snippet.html" },
};

export default aigosMetadata;
