/** Generated by AI Growth OS — merge into app/layout.tsx metadata */
export const aigosMetadata: Record<string, unknown> = {
  alternates: { canonical: "github://akibraza3723/Vantish/client/design.md" },
};

export default aigosMetadata;
