/** Generated by AI Growth OS — merge into app/layout.tsx metadata */
export const aigosMetadata: Record<string, unknown> = {
  // FAQ JSON-LD is in head-snippet.html (not Metadata API)
  other: { "aigos-faq": "see head-snippet.html" },
};

export default aigosMetadata;
